### ISSUE TITLE
Proposal: Speed up RSpec by deferring garbage collection

### ISSUE THREAD

**Issue by ipepe** [khasinski/rails-awesome-tests#1]
<https://makandracards.com/makandra/950-speed-up-rspec-by-deferring-garbage-collection>

**Comment by khasinski** [comment]
I've seen this one before, but I haven't found any reasonable improvement with it (in the projects I've worked on).

The main issue here is that most really slow test suites are struggling with databases and browser automation, GC is only a small fraction of the test suite runtime. And if your tests are CPU-bound and fast enough for GC to matter you usually already have a pretty fast test suite.

However, for the sake of completeness I'm willing to put this into the document. Can we actually test this code (and measure the improvements) in a few projects?

**Comment by ipepe** [comment]
In the last few days, I've been working on improving test suite time for a client and this definitely helped although not more than 20% (10s -> 8.5s for one specific example). 

As this repository/knowledge base focuses on slow test suites, for some people this might be an improvement that they are willing to implement. 

In my case, I found better optimizations and this change didn't calculate into huge benefits (for the 40m test suite, 10-20% is not enough)

**Comment by khasinski** [comment]
I've put it into #2 , feel free to voice your opinion if I'm missing anything
